#docker-compose cho master node
version: '3'
#khai bao bien duong dan redis
redis_path="/opt/redis-master"
redis_config_path="/opt/redis-master/conf"

#khai bao bien duong dan redis sentinel
redis_sentinel_path="/opt/redis-master/redis-sentinel"
redis_sentinel_config_path="/opt/redis-master/redis-sentinel/conf"

services:
#1. contaienr redis-master node
  redis-master:
    image: docker.io/library/redis:7.4.1-alpine3.20
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ${redis_config_path}/redis.conf:/usr/local/etc/redis/redis.conf
      - ${redis_path}data:/data
      - ${redis_path}logs:/data/logs
    networks:
      - redis-master-net
#2. contaienr redis-sentinel
  redis-sentinel:
    build:
      context: ./redis-sentinel
      dockerfile: Dockerfile
    container_name: redis-master-sentinel
    depends_on:
      - redis-master
    ports:
      - "26379:26379"
    volumes:
      - ${redis_sentinel_config_path}/sentinel.conf:/redis-sentinel/sentinel.conf
      - ${redis_sentinel_path}/data:/redis-sentinel/data
      - ${redis_sentinel_path}/logs:/redis-sentinel/logs
    networks:
      - redis-master-net
networks:
  redis-master-net:
    driver: bridge
